/**
 * This file was autogenerated from enemy-small.png by WiiBuilder.
 */

//---------------------------------------------------------------------------------
#ifndef _enemysmall_h_
#define _enemysmall_h_
//---------------------------------------------------------------------------------
extern const unsigned char enemysmall[];
extern const int enemysmall_size;
//---------------------------------------------------------------------------------
#endif //_enemy-small_h_
//---------------------------------------------------------------------------------
