/**
 * This file was autogenerated from gameSound.mp3 by WiiBuilder.
 */

//---------------------------------------------------------------------------------
#ifndef _gameSound_h_
#define _gameSound_h_
//---------------------------------------------------------------------------------
extern const unsigned char gameSound[];
extern const int gameSound_size;
//---------------------------------------------------------------------------------
#endif //_gameSound_h_
//---------------------------------------------------------------------------------
