/**
 * This file was autogenerated from laser-bolts.png by WiiBuilder.
 */

//---------------------------------------------------------------------------------
#ifndef _laserbolts_h_
#define _laserbolts_h_
//---------------------------------------------------------------------------------
extern const unsigned char laserbolts[];
extern const int laserbolts_size;
//---------------------------------------------------------------------------------
#endif //_laser-bolts_h_
//---------------------------------------------------------------------------------
