/**
 * This file was autogenerated from startMenu.png by WiiBuilder.
 */

//---------------------------------------------------------------------------------
#ifndef _startMenu_h_
#define _startMenu_h_
//---------------------------------------------------------------------------------
extern const unsigned char startMenu[];
extern const int startMenu_size;
//---------------------------------------------------------------------------------
#endif //_startMenu_h_
//---------------------------------------------------------------------------------
